### ISSUE TITLE
fgPlatformGlutSetWindowTitle fg_window_x11.c does not work with UTF-8

### ISSUE THREAD

**Issue by Safari77** [freeglut/freeglut#188] opened 2024-11-19 09:52 UTC
mupdf uses freeglut to set window title, UTF-8 characters in filenames are displayed incorrectly.
Currently freeglut uses XSetWMName which does not support UTF-8.
Fix would be to use Xutf8SetWMProperties. Example code in 
https://github.com/vim/vim/blob/master/src/os_unix.c#L2195

**Comment by jtsiomb** [comment] 2024-11-20 02:51
Thanks for the bug report.

I looked into it a little bit today. I added a check in cmake for the availability of Xutf8SetWMProperties, and looked into the EWMH conventions. Apparently the right thing to do is set UTF8 names in _NET_WM_NAME and _NET_WM_ICON_NAME properties, and only set ASCII names to the original ICCCM WM_NAME and WM_ICON_NAME properties (which is what XSetWMName does).

My current plan is to scan the string passed to glutSetWindowTitle and glutSetIconTitle, and set one or both depending on whether it contains non-ASCII characters. I hope to find some time to implement this in the next few days. Feel free to ping me if I haven't in more than a week.

**Comment by rcmaniac25** [comment] 2024-11-20 10:57
Just want to point out unicode was a thing that was being worked on at one point, but it's now been years: https://github.com/freeglut/freeglut/pull/62

**Comment by rcmaniac25** [comment] 2024-11-20 17:43
Sounds good. Just bringing it up.

**Comment by jtsiomb** [comment] 2024-11-25 03:53
Should be fixed in the latest commit (b39df05e257999f94b5c1e4d4fbbfb8759302bc9). Please verify, and reopen if there are any issues.

I only tested on my main GNU/Linux machine for now, but there are fallbacks in place, so I'll give it a test on older X11 implementations sometime during the next few days to exercise all code paths, and make sure it still builds and runs correctly everywhere.

**Comment by Safari77** [comment] 2024-11-25 10:05
Thanks. I have tried only with mupdf (changed Makethird `USE_SYSTEM_GLUT := yes` )
Proper UTF-8 string is passed to glutSetWindowTitle glutSetIconTitle . `xwininfo: Window id:` is okay, but window title is not:

mupdf-ssää€.epub
![mupdf-ssää€](https://github.com/user-attachments/assets/9bf25871-4ca8-4fc4-8fcb-81fc4c77cc5d)

mupdf-ssää€—2024.epub
![mupdf-ssää€—2024](https://github.com/user-attachments/assets/402522df-e7f2-4d29-9c7d-0b8d2dfb8460)

**Comment by jtsiomb** [comment] 2024-11-25 15:36
please check `xprop | grep NAME`. Is the title set to _NET_WM_NAME as UTF8_STRING?

**Comment by Safari77** [comment] 2024-11-25 15:59
> please check `xprop | grep NAME`. Is the title set to _NET_WM_NAME as UTF8_STRING?

`ssää€.epub`
```
_NET_WM_ICON_NAME(UTF8_STRING) = "ssää€.epub - 1/977 - 1/1"
_NET_WM_NAME(UTF8_STRING) = "ssää€.epub - 1/977 - 1/1"
WM_ICON_NAME(STRING) = "MuPDF: Loading..."
WM_NAME(STRING) = "MuPDF: Loading..."
WM_LOCALE_NAME(STRING) = "C"
```


`ssää€—2024.epub`
```
WM_ICON_NAME(STRING) = "ssÃ¤Ã¤â\302\202¬â\302\200\302\2242024.epub - 1/977 - 1/1"
WM_NAME(STRING) = "ssÃ¤Ã¤â\302\202¬â\302\200\302\2242024.epub - 1/977 - 1/1"
WM_LOCALE_NAME(STRING) = "C"
```

```
$ locale
LANG=en_GB.utf8
LC_CTYPE="en_GB.utf8"
LC_NUMERIC=fi_FI.utf8
LC_TIME=en_GB.UTF-8
LC_COLLATE=fi_FI.utf8
LC_MONETARY=fi_FI.utf8
LC_MESSAGES="en_GB.utf8"
LC_PAPER=fi_FI.utf8
LC_NAME=fi_FI.utf8
LC_ADDRESS=fi_FI.utf8
LC_TELEPHONE=fi_FI.utf8
LC_MEASUREMENT=fi_FI.utf8
LC_IDENTIFICATION=fi_FI.utf8
LC_ALL=
```

**Comment by jtsiomb** [comment] 2024-11-25 21:21
OK so the first one is correct but the second one gets mangled (because it's detected as an invalid utf8 sequence and falls back to the original XSetWMName method). Right?

I'm creating a file with the same filename (`ssää€—2024.epub`), and trying it with mupdf linked with the current version of freeglut, and it's detected correctly, and ends up in _NET_WM_NAME as a UTF8_STRING. Could attach the actual file here? Wipe it out if it has anything sensitive in it `cat /dev/null >ssää€—2024.epub`, but don't touch the filename. Maybe attach a tar-ed version too in case github does any filename sanitization on attached files.

**Comment by jtsiomb** [comment] 2024-11-25 23:00
Wait nevermind, I reproduced it. I don't know why I thought it worked before. Maybe the fact that my window manager shows it correctly even if it's in WM_NAME as STRING threw me off, even though I was sure I checked xprop... anyway...

I traced it with a debugger, and what's happening is that the string is passing my own utf8 validation, and passing it to `Xutf8TextListToTextProperty` to create a text property of the correct format to set to the window (see `set_utf8_title` in `src/x11/fg_window_x11.c`), but then `Xutf8TextListToTextProperty` fails, so I'm falling back to `XSetWMName` as before.

**Comment by jtsiomb** [comment] 2024-11-25 23:13
OK apparently Xutf8TextListToTextProperty can return a positive non-zero status to mean partial success, with the return value signifying how many bytes were left-over after conversion, and the result seems to be perfectly usable and no reason to fallback to `XSetWMName`.

The latest commit should work in all cases (d3799755874dfae53540caf75003dfed68738720). Please test and let me know if there's still an issue.

**Comment by ccxvii** [comment] 2024-11-28 14:01
This commit breaks setting titles on ancient window managers (such as minimalist ones that use XFetchName to read the window title) by not updating the WM_NAME property when it succeeds in setting _NET_WM_NAME.

I suggest unconditionally setting WM_NAME in addition to setting _NET_WM_NAME (optionally stripping any non-ASCII characters or replacing them with '?') instead.

**Comment by jtsiomb** [comment] 2024-11-28 21:24
Good idea, I'll do that.

**Comment by jtsiomb** [comment] 2024-11-29 04:21
Ok, I think I'm over-complicating this...

I'm already passing the string through, even if it was utf8 to WM_NAME, incorrectly tagged as type STRING, if we're building on a platform without the UTF8 Xlib extensions, because some window managers seem to cope fine with it and even show it correctly (fvwm does), and at worse it'll do what it did all this time, which might be to show gibberish.

I think my attempt to be absolutely "correct" is causing more trouble than it's solving, and complicating the code more than necessary. I think I'll just drop all scanning and detection of utf8 strings, and just pass everything through to WM_NAME as STRING like we used to, and if the UTF8 extensions are available I'll also pass it as UTF8_STRING to _NET_WM_NAME, and let the window managers deal with it. They are supposed to ignore WM_NAME if _NET_WM_NAME is set anyway, so it shouldn't make a difference on modern window managers.

**Comment by jtsiomb** [comment] 2024-11-29 05:35
done, commit: df3fc1abab7fd2aea1b283293ee49264a61fd787

**Closed by jtsiomb** 2024-11-29 05:35 UTC
