### ISSUE TITLE
duplicate symbols with clang ldd

### ISSUE THREAD

**Issue by KBentley57** [freeglut/freeglut#104] opened 2022-05-19 18:59 UTC
I'm using AMD's version of clang to compile, and I'm getting quite a few errors during the link.  The section below shows the errors, all of them relating to the same thing.  Any advice? Building with gcc works as expected.

CMake options:

-DCMAKE_CXX_STANDARD=11      
-DOPT_DOUBLE_PRECISION=OFF
-DBoost_USE_STATIC_LIBS=OFF
-DBUILD_SHARED_LIBS=ON

Using AOCC 3.2 from here https://developer.amd.com/amd-aocc/

```[ 31%] Linking C executable bin/Lorenz_static
/usr/bin/cmake -E cmake_link_script CMakeFiles/Lorenz_static.dir/link.txt --verbose=1
/opt/AMD/aocc-compiler-3.2.0/bin/clang -O3 -DNDEBUG -rdynamic CMakeFiles/Lorenz_static.dir/progs/demos/Lorenz/lorenz.c.o -o bin/Lorenz_static  -lGLU -lGL -lm -lX11 -lXi -lm lib/libglut.a -lGL -lm -lX11 -lXi 
ld.lld: error: duplicate symbol: fghGenBuffers
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghGenBuffers) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x0) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghDeleteBuffers
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghDeleteBuffers) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x8) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghBindBuffer
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghBindBuffer) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x10) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghBufferData
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghBufferData) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x18) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghVertexAttribPointer
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghVertexAttribPointer) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x20) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghEnableVertexAttribArray
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghEnableVertexAttribArray) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x28) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghDisableVertexAttribArray
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghDisableVertexAttribArray) in archive lib/libglut.a
>>> defined at fg_gl2.c
>>>            fg_gl2.c.o:(.bss+0x30) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghGenBuffers
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghGenBuffers) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x0) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghBindBuffer
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghBindBuffer) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x10) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghBufferData
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghBufferData) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x18) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghEnableVertexAttribArray
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghEnableVertexAttribArray) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x20) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghVertexAttribPointer
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghVertexAttribPointer) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x30) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghDisableVertexAttribArray
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghDisableVertexAttribArray) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x28) in archive lib/libglut.a

ld.lld: error: duplicate symbol: fghDeleteBuffers
>>> defined at fg_window.c
>>>            fg_window.c.o:(fghDeleteBuffers) in archive lib/libglut.a
>>> defined at fg_geometry.c
>>>            fg_geometry.c.o:(.bss+0x8) in archive lib/libglut.a
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/Lorenz_static.dir/build.make:111: bin/Lorenz_static] Error 1
make[2]: Leaving directory '/scratch/SupportPackages.AMD/build/fglut/src/freeglut-build'
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/Lorenz_static.dir/all] Error 2
make[1]: Leaving directory '/scratch/SupportPackages.AMD/build/fglut/src/freeglut-build'
make: *** [Makefile:149: all] Error 2
```

**Comment by jtsiomb** [comment] 2022-05-19 19:11
Which version of freeglut are you trying to build?

**Comment by KBentley57** [comment] 2022-05-20 20:34
Sorry, I must have let that detail slip.  The latest release, 3.2.2.

**Comment by jtsiomb** [comment] 2022-05-23 11:27
I tried to build with clang and link with lld, but could not reproduce the issue. So it must be something specific to the AMD version of clang you're using.

**Comment by jtsiomb** [comment] 2024-05-07 16:28
Since it's been two years, I assume it was a toolchain issue. Closing as invalid. Feel free to re-open if you think it was an actual problem with freeglut.

**Closed by jtsiomb** 2024-05-07 16:28 UTC
