### ISSUE TITLE
Freeglut not working as expected: failed to discover all needed compositor interfaces.

### ISSUE THREAD

**Issue by EmanuelMarquis** [freeglut/freeglut#164] opened 2024-05-02 22:25 UTC
For some reason, I get this error message from freeglut upon running the following snippet -> freeglut: failed to discover all needed compositor interfaces.
```
#include <GL/freeglut.h>

#define WINDOW_W 500
#define WINDOW_H 500

int main(int pargc, char** argv) {

    glutInit(&pargc, argv);
    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
    glutInitWindowSize(WINDOW_W, WINDOW_H);
    glutCreateWindow("Janelinha");

    glutMainLoop();
    return 0;
}
```
I don't get why it doesn't work, it builds fine and it just doesn't work... This is my cmake, I'm using freeglut from vcpkg. I tried building freeglut from source and I ran into the same issue
```
cmake_minimum_required(VERSION 3.10)

project(my-glut-project)

find_package(GLUT REQUIRED)

add_executable(${PROJECT_NAME} main.c)

target_link_libraries(${PROJECT_NAME} PRIVATE GLUT::GLUT)

```

**Comment by dcnieho** [comment] 2024-05-02 22:33
you fail to provide basic information: what platform are you running on?

**Comment by EmanuelMarquis** [comment] 2024-05-02 22:38
Linux - Ubuntu. Also, I'm using GCC

**Comment by jtsiomb** [comment] 2024-05-02 23:12
Googling that error message (because it's not coming from freeglut itself), brings up freeglut issue #72

Looks like you're trying to use a version of freeglut compiled for wayland. Our wayland backend is broken for some time, and nobody who cares about wayland stepped up to fix it. Please use a version of freeglut compiled for X11/GLX instead (which is the default build option if you don't actively select wayland).

I'm pretty sure the ubuntu freeglut package is compiled for X11, so you could just use that if you don't want to compile freeglut yourself. Install it with apt.

Closing as a duplicate of issue #72

**Closed by jtsiomb** 2024-05-02 23:12 UTC

**Comment by EmanuelMarquis** [comment] 2024-05-03 12:49
thanks! I tried the X11 version and now it works fine <3
